songsite/song/urls.py
from django.urls import path
import song.views as views

app_name = 'song'
urlpatterns = [
    path('songs/', views.SongList.as_view(), name='song_list'),
    path('songs/<int:song_id>/', views.show_song_detail, name='song_detail'),
    path('songs/<int:song_id>/comment/', views.comment, name='song_comment'),
    path('comment/<int:comment_id>/delete', views.del_comment, name='delete_comment'),
    path('artists/', views.ArtistList.as_view(), name='artist_list'),
    path('artists/<int:pk>/', views.ArtistDetail.as_view(), name='artist_detail'),
    path('check/', views.check, name='check')
]

songsite/songsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('song/', include('song.urls'))
]

songsite/song/models.py
from django.db import models

# Create your models here.

class Artist(models.Model):

    """The model of an artist.
    
    This class is the model of artists in this site. There are two types of artists in this site:
    the ones who have a specific page for their introduction, and the ones who just have their 
    names appear in the site because he/she is one of the artists who made contributions in a song
    in this site.  

    Attributes:
        name (CharField): 
            the artist's name. It is the only required attribute because this site shows the name
            of both types of artists
        alias (CharField):
            only occured for the artists who have their intro and has other names
        original_id (CharField):
            the artist's id in the original website (for the many to many relation link)
        intro (CharField):
            the artist's intro, occured only for the artists who have their intro
        history (CharField):
            the artist's hitstory, occured only for the artists who have intro
            in this site and have history part in the original site
        master_work (CharField):
            the artist's master work, occured only for the artists who have intro
            in this site and have master work part in the original site
        milestones (CharField):
            the artist's milestones, occured only for the artists who have intro in
            this site and have milestones part in the original site
        url (CharField):
            the url of the artist's original webpage, occured only for the artists who have
            intro in this site
    """

    name = models.CharField(max_length=50)
    alias = models.CharField(max_length=50, null=True, blank=True)
    original_id = models.CharField(max_length=15, null=True, blank=True)
    intro = models.CharField(max_length=2000, null=True, blank=True)
    history = models.CharField(max_length=10000, null=True, blank=True)
    master_work = models.JSONField(default=list, null=True, blank=True)
    milestones = models.JSONField(default=list, null=True, blank=True)
    original_url = models.CharField(max_length=50, null=True, blank=True)

class Song(models.Model):

    """The model of a song

    This class is the model of songs in this site. Its attributes contain information about the song

    Attributes:
        name (CharField): the song's name
        alias (CharField): the song's other name (if it has one)
        original_id (CharField): the song's id in the original website (for the manytomany relation link)
        original_url (CharField): the song's url in the original website
        artist (ManyToManyField): the artist contributed for the song
        lyrics (CharField): the lyrics of the song
    """

    name = models.CharField(max_length=50)
    alias = models.CharField(max_length=50, null=True, blank=True)
    original_id = models.CharField(max_length=15)
    original_url = models.CharField(max_length=50)
    artist = models.ManyToManyField('Artist')
    lyrics = models.CharField(max_length=2000)

class Comment(models.Model):

    """The model of a comment

    This class is the model of a comment in this site. You can make comments under any song.

    Attributes:
        song (ForeignKey): which song is this comment under
        user (CharField): the user of this comment
        comment_text (CharField): the text in the comment
        pub_date (DateTimeField): the publication date and time of this comment
    """

    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    user = models.CharField(max_length=50)
    comment_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('发布时间', auto_now_add=True)

class SongSegment(models.Model):

    """The song segment model (for the inverted index of songs)

    This model is for all song segments/tokens appear in the song objects of this site.

    Attributes:
        token (CharField): the token for index
        df (PositiveIntegerField): document frequency
    """

    token = models.CharField(max_length=20, unique=True) # setting unique=True for making the index
    df = models.PositiveIntegerField()

class SongIndex(models.Model):

    """The song index model

    This class is the index for recording each token has appeared in what song document with
    how many times. 

    Attributes:
        article_id (PositiveIntegerField): the song document's id
        tf (PositiveIntegerField): term frequency in this document
        song_segment (ForeignKey): the corresponding song segment/token
    """

    article_id = models.PositiveIntegerField()
    tf = models.PositiveIntegerField()
    song_segment = models.ForeignKey(SongSegment, on_delete=models.CASCADE)

class ArtistSegment(models.Model):

    """The artist segment model (for the inverted index of songs)

    This model is for all artist segments/tokens appear in the artist objects of this site.

    Attributes:
        token (CharField): the token for index
        df (PositiveIntegerField): document frequency
    """

    token = models.CharField(max_length=20, unique=True)
    df = models.PositiveIntegerField()

class ArtistIndex(models.Model):

    """The artist index model

    This class is the index for recording each token has appeared in what artist document with
    how many times. 

    Attributes:
        article_id (PositiveIntegerField): the artist document's id
        tf (PositiveIntegerField): term frequency in this document
        song_segment (ForeignKey): the corresponding song segment/token
    """

    article_id = models.PositiveIntegerField()
    tf = models.PositiveIntegerField()
    artist_segment = models.ForeignKey(ArtistSegment, on_delete=models.CASCADE)

songsite/song/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.db.models import Case, When
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.core.cache import cache
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Song, Artist, Comment, SongSegment, SongIndex, ArtistSegment, ArtistIndex
import jieba
import math
import time
import hashlib
import json

# Create your views here.

class SongList(generic.ListView):

    """The class for the song list view.

    This class, inherited from ListView, constructs the view for the song list.

    Attributes:
        model (class): the model used by this view
        template_name (str): the name of the template used by this view
        context_object_name (str):
            the name of the context object that contains the returns from
            the get_queryset function
        paginate_by (int): how many songs should appear in each page
        get_queryset (QuerySet[Any]): returns the list that would be shown in the view
    """

    model = Song
    template_name = 'song/songList.html'
    context_object_name = 'all_songs_list'
    paginate_by = 20

    def get_queryset(self) -> QuerySet[Any]:
        return Song.objects.all()
    
def show_song_detail(request, song_id):

    """Function of the song detail's view

    This function constructs the view of a song's detail, which contains the information
    of the song and the comments under it

    Args:
        request: the request to the site
        song_id: the id of the song in this site
    """

    song = get_object_or_404(Song, pk=song_id)
    comments = song.comment_set.order_by('-pub_date') # order by publication time from new to old
    return render(
        request,
        'song/songDetail.html',
        {
            'song': song,
            'comments': comments
        },
    )
    
class ArtistList(generic.ListView):

    """The class for the artist list view.

    This class, inherited from ListView, constructs the view for the artist list.

    Attributes:
        model (class): the model used by this view
        template_name (str): the name of the template used by this view
        context_object_name (str):
            the name of the context object that contains the returns from
            the get_queryset function
        paginate_by (int): how many songs should appear in each page
        get_queryset (QuerySet[Any]):
            returns the list that would be shown in the view. In this function, the artist without
            original url is filtered out because all Artist objects that only names in this site,
            which should not be in the list, do not have original_url.
    """

    model = Artist
    template_name = 'song/artistList.html'
    context_object_name = 'all_artists_list'
    paginate_by = 20

    def get_queryset(self) -> QuerySet[Any]:
        return Artist.objects.filter(original_url__isnull=False)

class ArtistDetail(generic.DetailView):

    """The class for the artist detail.

    This class constructs the view of an artist's detail.

    Attributes:
        model (class): the model used in this view
        template (str): the name of the template needed to be rendered
    """

    model = Artist
    template_name = 'song/artistDetail.html'

def comment(request, song_id):

    """The function for making comments

    This function enables users to make comments under songs. In the post request, it will get
    the username and text from the user. If there are missing information, it will show an error
    message on the page that prompt the user to input all needed information. Then, after getting
    full information, it will show the comments under the song.

    Args:
        request:
            the post request to the website. In this function, a complete request contains username
            ('user') and text ('comment_text')
        song_id: the id of the song that will be commented
    """

    song = get_object_or_404(Song, pk=song_id)
    data = request.POST
    user = data['user']
    comment_text = data['comment_text']
    comment_obj = Comment(song=song, user=user, comment_text=comment_text)
    comments = song.comment_set.order_by('-pub_date') # order by publication time from new to old
    try:
        # try to check if the comment object is complete
        comment_obj.full_clean()
    except ValidationError:
        # if not, render the same song page with the error message
        return render(
            request,
            'song/songDetail.html',
            {
                'song': song,
                'comments': comments,
                'error_message': '请再次检查您已填入了用户名和评论',
            }
        )
    else:
        # redirect to the song page with the new comment
        comment_obj.save()
        return HttpResponseRedirect(reverse('song:song_detail', args=(song.id, )))
    
def del_comment(request, comment_id):

    """The delete comment function.

    This function enables users to delete any comment seen under a song. After
    deleting the comment object, it will redirect to the song page again without
    the deleted comment.

    Args:
        request: the request to the website
        comment_id: the id of the comment will be deleted
    """

    comment = get_object_or_404(Comment, pk=comment_id)
    song_id = int(request.POST['song_id']) # get which song that the deleted comment is under
    comment.delete()
    return HttpResponseRedirect(reverse('song:song_detail', args=(song_id, )))

def check(request):

    """The search/check function.

    This function enables users to search/check on songs/artists by entering a query. Then, 
    this query will be cut in to tokens by the jiaba package, and each token will have a tfidf
    score for each doct. Lastly, each doc's score on each token will be added together, and the 
    function will give a found_doc list to the render function ordered by the score from high
    to low. This function will also record the time for the whole search process.

    Args:
        request:
            the get request to the site. In this function, a complete request contains the query
            and the which set of doc (song/artist) does the user wants to search in ('class_')
    """

    query = request.GET.get('query')
    class_ = request.GET.get('class_')
    page_number = request.GET.get('page', 1)

    start_time = time.time() # record the start time
    if query is None and class_ is None:
        # this happens when the user first goes to the search url, so no information is sent to 
        # the render function
        return render(request, 'song/check.html')
    elif query is None or query.strip() == "":
        # the query is empty, prompt the user for query
        return render(
            request,
            'song/check.html',
            {
                'error_message': '请输入您的问题'
            }
        )
    elif class_ is None:
        # the class is empty, prompt the user for the class (song/artist)
        return render(
            request,
            'song/check.html',
            {
                'error_message': '请输入您想要查找的类别（歌曲/歌手）'
            }
        )
    else:
        # the request is complete

        # generate a unique cache key for the search
        cache_key = f"search_{hashlib.md5(f'{query}_{class_}'.encode()).hexdigest()}"
        cached_results = cache.get(cache_key)

        if cached_results:
            # the results are in the cache, no need to search again
            doc_id_list = cached_results['doc_id_list']
            elapsed_time = cached_results['elapsed_time']
            start_time = time.time() # pagination time
        else:
            query_seg = jieba.cut_for_search(query)
            found_doc = False # a flag for whether there is doc found
            tfidf_list = [] # the tfidf for each token in each doc

            def get_score(tfidf_list: list[dict[int, float]]) -> dict[int, float]:

                """the tfidf to doc score convert function.

                This function converts the tfidf for each token in each doc into the scores of
                each doc got on this query.

                Args:
                    tfidf_list (list[dict[int, float]]):
                        the tfidf for each token in each doc. The list is for each token. In each dictionary,
                        the int part is the doc_num, and the float part is the tfidf value.

                Returns:
                    score (dict[int, float]): the score of each_doc on this query.
                """

                score = {}
                # adding the score of each doc on all tokens together
                for tfidf in tfidf_list:
                    for doc_id in tfidf:
                        if doc_id in score:
                            score[doc_id] += tfidf[doc_id]
                        else:
                            score[doc_id] = tfidf[doc_id]
                return score

            if class_ == 'song':
                # client chose to search on songs, the total number should be the total number
                # of songs.
                N = Song.objects.count()
                for seg in query_seg:
                    try:
                        song_seg = SongSegment.objects.get(token=seg)
                    except SongSegment.DoesNotExist:
                        # the segment is not in the index, continue to next
                        continue
                    else:
                        # found the segment, calculate the tfidf for this segment/token in each
                        # document, and append this dict to the tfidf_list
                        if not found_doc:
                            found_doc = True
                        index_set = song_seg.songindex_set.all()

songsite/song/templates/song/artistDetail.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ artist.name }}详情</title>
    <link rel="stylesheet" href="{% static 'song/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'song/css/artistdetail.css' %}">
</head>
<body>
    <nav class="navbar">
        <ul class="nav-menu">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'song:song_list' %}">歌曲</a>
            </li>
            <li class="nav-item">
                <a class="nav-active-link" href="{% url 'song:artist_list' %}">歌手</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'song:check' %}">搜索</a>
            </li>
        </ul>
    </nav>

    <div class="artist-info">
        <h1 class="artist-name">{{ artist.name }}</h1>
        {% if artist.alias %}
            <h3 class="artist-alias">又名：{{ artist.alias }}</h3>
        {% endif %}
        <p><a href="{{ artist.original_url }}">原网站地址</a></p>
        {% with 'song/images/artist'|add:artist.original_id|add:'.jpg' as image_path %}
        <div class="artist-image-block">
            <img src="{% static image_path %}" alt="歌手图片" class="artist-image">
        </div>
        {% endwith %}
        <div class="artist-fieldblock">
            <fieldset class="artist-fieldset">
                <legend><h2 class="artist-block-header">歌手简介</h2></legend>
                <p>{{ artist.intro }}</p>
            </fieldset>
        </div>
        {% if artist.history %}
            <div class="artist-fieldblock">
                <fieldset class="artist-fieldset">
                    <legend><h2 class="artist-block-header">演艺生涯</h2></legend>
                    <p>{{ artist.history }}</p>
                </fieldset>
            </div>
        {% endif %}
        {% if artist.master_work %}
            <div class="artist-fieldblock">
                <fieldset class="artist-fieldset">
                    <legend><h2 class="artist-block-header">代表作品</h2></legend>
                    {% if artist.master_work|length == 1 %}
                        <p>{{ artist.master_work.0 }}</p>
                    {% else %}
                        <ul>
                            {% for work in artist.master_work %}
                                <li>{{ work }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </fieldset>
            </div>
        {% endif %}
        {% if artist.milestones %}
            <div class="artist-fieldblock">
                <fieldset class="artist-fieldset">
                    <legend><h2 class="artist-block-header">里程碑</h2></legend>
                    {% if artist.milestones|length == 1 %}
                        <p>{{ artist.milestones.0 }}</p>
                    {% else %}
                        <ul>
                            {% for milestone in artist.milestones %}
                                <li>{{ milestone }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </fieldset>
            </div>
        {% endif %}
        <div class="artist-fieldblock">
            <fieldset class="artist-fieldset">
                <legend><h2 class="artist-block-header">站内歌曲</h2></legend>
                {% if artist.song_set.all %}
                    <ul>
                        {% for song in artist.song_set.all %}
                            <li><a href="{% url 'song:song_detail' song.id %}">{{ song.name }}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>暂无歌曲</p>
                {% endif %}
            </fieldset>
        </div>
    </div>
</body>
</html>

songsite/song/templates/song/artistList.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<header>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>歌手列表</title>
    <link rel="stylesheet" href="{% static 'song/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'song/css/artistcard.css' %}">
</header>
<body>
    <nav class="navbar">
        <ul class="nav-menu">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'song:song_list' %}">歌曲</a>
            </li>
            <li class="nav-item">
                <a class="nav-active-link" href="{% url 'song:artist_list' %}">歌手</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'song:check' %}">搜索</a>
            </li>
        </ul>
    </nav>
    <div class="artist-list">
        {% if all_artists_list %}
            <ul class="artist-menu">
                {% for artist in all_artists_list %}
                    <li class="artist-item">
                        <fieldset class="artist-fieldset">
                            <legend class="artist-legend">
                                <a href="{% url 'song:artist_detail' artist.id %}">{{ artist.name }}</a>
                            </legend>
                            <div class="artist-content">
                                <div class="artist-image">
                                    <a href="{% url 'song:artist_detail' artist.id %}">
                                        {% with 'song/images/artist'|add:artist.original_id|add:'.jpg' as image_path %}
                                        <img src="{% static image_path %}"
                                            alt="歌手图片"
                                            class="artist-photo"
                                        >
                                        {% endwith %}
                                    </a>
                                </div>

                                <div class="artist-intro">
                                    <p>{{ artist.intro|truncatechars:100 }}</p>
                                </div>
                            </div>
                        </fieldset>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No artists</p>
        {% endif %}
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; 首页</a>
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}

            <span class="current">
                第{{ page_obj.number }}页，共{{ page_obj.paginator.num_pages }}页
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">尾页 &raquo;</a>
            {% endif %}

            <form method="get">
                <input
                    type="number"
                    name="page"
                    min="1"
                    max="{{ page_obj.pagination.num_pages }}"
                    placeholder="页码"
                    required
                >
                <button type="submit">跳转</button>
            </form>
        </span>
    </div>
</body>
</html>

songsite/song/templates/song/songDetail.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<header>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ song.name }}详情</title>
    <link rel="stylesheet" href="{% static 'song/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'song/css/songdetail.css' %}">
    <link rel="stylesheet" href="{% static 'song/css/comment.css' %}">
</header>
<body>
    <nav class="navbar">
        <ul class="nav-menu">
            <li class="nav-item">
                <a class="nav-active-link" href="{% url 'song:song_list' %}">歌曲</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'song:artist_list' %}">歌手</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'song:check' %}">搜索</a>
            </li>
        </ul>
    </nav>
    <div class="song-intro">
        <div class="song-introtext">
            <h1 class="song-name">{{ song.name }}</h1>
            {% if song.alias %}
                <h3 class="song-alias">{{ song.alias }}</h3>
            {% endif %}
            <p>歌手：</p>
            <ul class="song-artists">
                {% for artist in song.artist.all %}
                    {% if artist.original_url %}
                        <li class="song-artist"><a href="{% url 'song:artist_detail' artist.id %}">{{ artist.name }}</a></li>
                    {% else %}
                        <li class="song-artist">{{ artist.name }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
            <p><a href="{{ song.original_url }}">原歌曲网站</a></p>
        </div>
        <div class="song-image">
            {% with 'song/images/song'|add:song.original_id|add:'.jpg' as image_path %}
                <img src="{% static image_path %}" alt="歌曲图片">
            {% endwith %}
        </div>
    </div>
    <div class="song-lyrics">
        <p>歌词：</p>
        {{ song.lyrics|safe }}
    </div>
    <div class="comment">
        <p class="comment-title">评论：</p>
        {% if comments %}
            <div class="comment-list">
                {% for comment in comments %}
                    <fieldset class="comment-fieldset">
                        <legend><h2>{{ comment.user }}</h2></legend>
                        <p class="comment-pubtime">发布时间：{{ comment.pub_date }}</p>
                        <p>内容：{{ comment.comment_text }}</p>
                        <form method="post" action="{% url 'song:delete_comment' comment.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="song_id" value="{{ song.id }}">
                            <input type="submit" value="删除">
                        </form>
                    </fieldset>
                {% endfor %}
            </div>
        {% else %}
        <p>暂无评论</p>
        {% endif %}
    </div>
    <form action="{% url 'song:song_comment' song.id %}" method="post" class="input-form">
        {% csrf_token %}
        {% if error_message %}
            {{ error_message }}
        {% endif %}
        用户名: <input type="text" name="user">
        内容：<input type="text" name="comment_text" class="input-content">
        <input type="submit" value="提交">
    </form>
</body>
</html>

songsite/song/templates/song/songList.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<header>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>歌曲列表</title>
    <link rel="stylesheet" href="{% static 'song/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'song/css/songcard.css' %}">
</header>
<body>
    <nav class="navbar">
        <ul class="nav-menu">
            <li class="nav-item">
                <a class="nav-active-link" href="{% url 'song:song_list' %}">歌曲</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'song:artist_list' %}">歌手</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'song:check' %}">搜索</a>
            </li>
        </ul>
    </nav>
    <div class="song-list">
        {% if all_songs_list %}
            <ul class="song-menu">
                {% for song in all_songs_list %}
                    <li class="song-item">
                        <div class="song-block">
                            <div class="song-image-component">
                                {% with 'song/images/song'|add:song.original_id|add:'.jpg' as image_path %}
                                <a href="{% url 'song:song_detail' song.id %}">
                                    <img
                                        src="{% static image_path %}"
                                        alt="歌曲图片"
                                        class="song-image"
                                    >
                                </a>
                                {% endwith %}
                            </div>

                            <div class="song-intro">
                                <h2 class="song-name">
                                    <a href="{% url 'song:song_detail' song.id %}">{{ song.name }}</a>
                                </h2>
                                <p>歌手：</p>
                                <ul class="song-artists">
                                    {% for artist in song.artist.all %}
                                        <li class="song-artist">{{ artist.name }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No songs</p>
        {% endif %}
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; 首页</a>
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}

            <span class="current">
                第{{ page_obj.number }}页，共{{ page_obj.paginator.num_pages }}页
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">尾页 &raquo;</a>
            {% endif %}

            <form method="get">
                <input
                    type="number"
                    name="page"
                    min="1"
                    max="{{ page_obj.pagination.num_pages }}"
                    placeholder="页码"
                    required
                >
                <button type="submit">跳转</button>
            </form>
        </span>
    </div>
</body>
</html>